name: servicios-cancion
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pydub
  - requests
  - fastapi
  - uvicorn
  - python-dotenv
  - pyngrok
  - pip:
      - openai-whisper @ git+https://github.com/openai/whisper.git@517a43ecd132a2089d85f4ebc044728a71d49f6e
      - transformers==4.51.3
      - torch==2.7.0
      - sentencepiece==0.2.0
      - sacremoses==0.1.1
      - tqdm==4.67.1
      - starlette==0.46.2
      - python-multipart==0.0.20
      - safetensors==0.5.3
      - typing-inspection==0.4.0
      - typing_extensions==4.13.2
      - tiktoken==0.9.0
      - huggingface-hub==0.31.1
      - filelock==3.18.0
      - regex==2024.11.6
      - sniffio==1.3.1
      - sympy==1.14.0
      - more-itertools==10.7.0
      - MarkupSafe==3.0.2
      - Jinja2==3.1.6
      - joblib==1.5.0
      - llvmlite==0.44.0
      - numba==0.61.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - fsspec==2025.3.2
      - idna==3.10
      - colorama==0.4.6
      - click==8.2.0
      - certifi==2025.4.26
      - httpx==0.28.1
      - httpcore==1.0.9
      - pydantic==2.11.4
      - pydantic_core==2.33.2
      - dotenv==0.9.9
